apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:hub-of-hubs-proxy-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:hub-of-hubs-proxy-server
subjects:
  - kind: ServiceAccount
    name: hub-of-hubs-proxy-server-sa
    namespace: open-cluster-management
